#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_COLON_EQ = 1,
  sym_statement_skip = 2,
  anon_sym_SEMI = 3,
  anon_sym_if = 4,
  anon_sym_then = 5,
  anon_sym_else = 6,
  anon_sym_while = 7,
  anon_sym_do = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  sym_predicate_true = 11,
  sym_predicate_false = 12,
  anon_sym_not = 13,
  anon_sym_and = 14,
  anon_sym_or = 15,
  sym_lt = 16,
  sym_le = 17,
  sym_eq = 18,
  sym_gt = 19,
  sym_ge = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  sym_expression_variable = 23,
  sym_expression_number = 24,
  anon_sym_PLUS = 25,
  anon_sym_DASH = 26,
  anon_sym_STAR = 27,
  anon_sym_SLASH = 28,
  sym_source_file = 29,
  sym_statements = 30,
  sym_statement = 31,
  sym_statement_assignment = 32,
  sym_statement_sequence = 33,
  sym_statement_if_then_else = 34,
  sym_statement_while_do = 35,
  sym_statement_block = 36,
  sym_predicate = 37,
  sym_predicate_negation = 38,
  sym_predicate_conjunction = 39,
  sym_predicate_disjunction = 40,
  sym_predicate_comparison = 41,
  sym_comparison_operator = 42,
  sym_parenthesized_predicate = 43,
  sym_expression = 44,
  sym_expression_addition = 45,
  sym_expression_subtraction = 46,
  sym_expression_multiplication = 47,
  sym_expression_division = 48,
  sym_parenthesized_expression = 49,
  aux_sym_statements_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_EQ] = ":=",
  [sym_statement_skip] = "statement_skip",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_do] = "do",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_predicate_true] = "predicate_true",
  [sym_predicate_false] = "predicate_false",
  [anon_sym_not] = "not",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [sym_lt] = "lt",
  [sym_le] = "le",
  [sym_eq] = "eq",
  [sym_gt] = "gt",
  [sym_ge] = "ge",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_expression_variable] = "expression_variable",
  [sym_expression_number] = "expression_number",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_source_file] = "source_file",
  [sym_statements] = "statements",
  [sym_statement] = "statement",
  [sym_statement_assignment] = "statement_assignment",
  [sym_statement_sequence] = "statement_sequence",
  [sym_statement_if_then_else] = "statement_if_then_else",
  [sym_statement_while_do] = "statement_while_do",
  [sym_statement_block] = "statement_block",
  [sym_predicate] = "predicate",
  [sym_predicate_negation] = "predicate_negation",
  [sym_predicate_conjunction] = "predicate_conjunction",
  [sym_predicate_disjunction] = "predicate_disjunction",
  [sym_predicate_comparison] = "predicate_comparison",
  [sym_comparison_operator] = "comparison_operator",
  [sym_parenthesized_predicate] = "parenthesized_predicate",
  [sym_expression] = "expression",
  [sym_expression_addition] = "expression_addition",
  [sym_expression_subtraction] = "expression_subtraction",
  [sym_expression_multiplication] = "expression_multiplication",
  [sym_expression_division] = "expression_division",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [aux_sym_statements_repeat1] = "statements_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_statement_skip] = sym_statement_skip,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_predicate_true] = sym_predicate_true,
  [sym_predicate_false] = sym_predicate_false,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [sym_lt] = sym_lt,
  [sym_le] = sym_le,
  [sym_eq] = sym_eq,
  [sym_gt] = sym_gt,
  [sym_ge] = sym_ge,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_expression_variable] = sym_expression_variable,
  [sym_expression_number] = sym_expression_number,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_source_file] = sym_source_file,
  [sym_statements] = sym_statements,
  [sym_statement] = sym_statement,
  [sym_statement_assignment] = sym_statement_assignment,
  [sym_statement_sequence] = sym_statement_sequence,
  [sym_statement_if_then_else] = sym_statement_if_then_else,
  [sym_statement_while_do] = sym_statement_while_do,
  [sym_statement_block] = sym_statement_block,
  [sym_predicate] = sym_predicate,
  [sym_predicate_negation] = sym_predicate_negation,
  [sym_predicate_conjunction] = sym_predicate_conjunction,
  [sym_predicate_disjunction] = sym_predicate_disjunction,
  [sym_predicate_comparison] = sym_predicate_comparison,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_parenthesized_predicate] = sym_parenthesized_predicate,
  [sym_expression] = sym_expression,
  [sym_expression_addition] = sym_expression_addition,
  [sym_expression_subtraction] = sym_expression_subtraction,
  [sym_expression_multiplication] = sym_expression_multiplication,
  [sym_expression_division] = sym_expression_division,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [aux_sym_statements_repeat1] = aux_sym_statements_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_statement_skip] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_predicate_true] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate_false] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_le] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_ge] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_expression_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statements] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_statement_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_if_then_else] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_while_do] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_block] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_predicate_negation] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate_disjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_parenthesized_predicate] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_expression_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_subtraction] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_multiplication] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_division] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_statements_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_right = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 16,
  [17] = 14,
  [18] = 16,
  [19] = 12,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 22,
  [27] = 23,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 11,
  [33] = 7,
  [34] = 8,
  [35] = 9,
  [36] = 10,
  [37] = 6,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 45,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 48,
  [52] = 52,
  [53] = 53,
  [54] = 50,
  [55] = 55,
  [56] = 49,
  [57] = 53,
  [58] = 52,
  [59] = 28,
  [60] = 30,
  [61] = 29,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 64,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 71,
  [73] = 73,
  [74] = 73,
  [75] = 38,
  [76] = 40,
  [77] = 77,
  [78] = 77,
  [79] = 39,
  [80] = 41,
  [81] = 42,
  [82] = 82,
  [83] = 83,
  [84] = 82,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '(', 58,
        ')', 59,
        '*', 81,
        '+', 79,
        '-', 80,
        '/', 82,
        ':', 3,
        ';', 35,
        '<', 53,
        '=', 55,
        '>', 56,
        'a', 20,
        'd', 22,
        'e', 17,
        'f', 4,
        'i', 11,
        'n', 23,
        'o', 25,
        's', 16,
        't', 12,
        'w', 13,
        '{', 43,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(58);
      if (lookahead == 'f') ADVANCE(60);
      if (lookahead == 'n') ADVANCE(71);
      if (lookahead == 't') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '(', 58,
        ')', 59,
        '*', 81,
        '+', 79,
        '-', 80,
        '/', 82,
        ':', 3,
        ';', 35,
        '<', 53,
        '=', 55,
        '>', 56,
        'i', 64,
        's', 68,
        'w', 65,
        '{', 43,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_statement_skip);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_statement_skip);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_if);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_while);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_predicate_true);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_predicate_true);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_predicate_false);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_predicate_false);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_not);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_le);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ge);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'a') ADVANCE(70);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'e') ADVANCE(41);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'e') ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'e') ADVANCE(48);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'f') ADVANCE(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'h') ADVANCE(67);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'i') ADVANCE(72);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'i') ADVANCE(69);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'k') ADVANCE(66);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'l') ADVANCE(61);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'l') ADVANCE(74);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'o') ADVANCE(75);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'p') ADVANCE(34);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'r') ADVANCE(76);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 's') ADVANCE(63);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 't') ADVANCE(50);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_expression_variable);
      if (lookahead == 'u') ADVANCE(62);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_expression_variable);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_expression_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 30},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 30},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 30},
  [29] = {.lex_state = 30},
  [30] = {.lex_state = 30},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 30},
  [39] = {.lex_state = 30},
  [40] = {.lex_state = 30},
  [41] = {.lex_state = 30},
  [42] = {.lex_state = 30},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 30},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [sym_statement_skip] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_predicate_true] = ACTIONS(1),
    [sym_predicate_false] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_le] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_ge] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_expression_number] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(83),
    [sym_statements] = STATE(85),
    [sym_statement] = STATE(44),
    [sym_statement_assignment] = STATE(38),
    [sym_statement_sequence] = STATE(38),
    [sym_statement_if_then_else] = STATE(38),
    [sym_statement_while_do] = STATE(38),
    [sym_statement_block] = STATE(38),
    [sym_expression] = STATE(30),
    [sym_expression_addition] = STATE(6),
    [sym_expression_subtraction] = STATE(6),
    [sym_expression_multiplication] = STATE(6),
    [sym_expression_division] = STATE(6),
    [sym_parenthesized_expression] = STATE(6),
    [aux_sym_statements_repeat1] = STATE(3),
    [sym_statement_skip] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_while] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_expression_variable] = ACTIONS(13),
    [sym_expression_number] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(19), 1,
      sym_statement_skip,
    ACTIONS(22), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(28), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      sym_expression_variable,
    ACTIONS(37), 1,
      sym_expression_number,
    STATE(2), 1,
      aux_sym_statements_repeat1,
    STATE(30), 1,
      sym_expression,
    STATE(44), 1,
      sym_statement,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(38), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [49] = 13,
    ACTIONS(3), 1,
      sym_statement_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_expression_variable,
    ACTIONS(15), 1,
      sym_expression_number,
    STATE(2), 1,
      aux_sym_statements_repeat1,
    STATE(30), 1,
      sym_expression,
    STATE(44), 1,
      sym_statement,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(38), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [98] = 13,
    ACTIONS(3), 1,
      sym_statement_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_expression_variable,
    ACTIONS(15), 1,
      sym_expression_number,
    STATE(3), 1,
      aux_sym_statements_repeat1,
    STATE(30), 1,
      sym_expression,
    STATE(44), 1,
      sym_statement,
    STATE(84), 1,
      sym_statements,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(38), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [146] = 13,
    ACTIONS(3), 1,
      sym_statement_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_expression_variable,
    ACTIONS(15), 1,
      sym_expression_number,
    STATE(3), 1,
      aux_sym_statements_repeat1,
    STATE(30), 1,
      sym_expression,
    STATE(44), 1,
      sym_statement,
    STATE(82), 1,
      sym_statements,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(38), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [194] = 2,
    ACTIONS(44), 6,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_expression_variable,
    ACTIONS(42), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_expression_number,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [219] = 2,
    ACTIONS(48), 6,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_expression_variable,
    ACTIONS(46), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_expression_number,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [244] = 4,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(52), 6,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_expression_variable,
    ACTIONS(50), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_expression_number,
      anon_sym_PLUS,
      anon_sym_DASH,
  [273] = 4,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(60), 6,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_expression_variable,
    ACTIONS(58), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_expression_number,
      anon_sym_PLUS,
      anon_sym_DASH,
  [302] = 2,
    ACTIONS(64), 6,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_expression_variable,
    ACTIONS(62), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_expression_number,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [327] = 2,
    ACTIONS(68), 6,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_expression_variable,
    ACTIONS(66), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_expression_number,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [352] = 11,
    ACTIONS(70), 1,
      sym_statement_skip,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_while,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      sym_expression_variable,
    ACTIONS(82), 1,
      sym_expression_number,
    STATE(60), 1,
      sym_expression,
    STATE(78), 1,
      sym_statement,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(75), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [394] = 11,
    ACTIONS(3), 1,
      sym_statement_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_expression_variable,
    ACTIONS(15), 1,
      sym_expression_number,
    STATE(30), 1,
      sym_expression,
    STATE(42), 1,
      sym_statement,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(38), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [436] = 11,
    ACTIONS(3), 1,
      sym_statement_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_expression_variable,
    ACTIONS(15), 1,
      sym_expression_number,
    STATE(30), 1,
      sym_expression,
    STATE(40), 1,
      sym_statement,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(38), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [478] = 11,
    ACTIONS(70), 1,
      sym_statement_skip,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_while,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      sym_expression_variable,
    ACTIONS(82), 1,
      sym_expression_number,
    STATE(60), 1,
      sym_expression,
    STATE(81), 1,
      sym_statement,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(75), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [520] = 11,
    ACTIONS(70), 1,
      sym_statement_skip,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_while,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      sym_expression_variable,
    ACTIONS(82), 1,
      sym_expression_number,
    STATE(60), 1,
      sym_expression,
    STATE(79), 1,
      sym_statement,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(75), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [562] = 11,
    ACTIONS(70), 1,
      sym_statement_skip,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_while,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      sym_expression_variable,
    ACTIONS(82), 1,
      sym_expression_number,
    STATE(60), 1,
      sym_expression,
    STATE(76), 1,
      sym_statement,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(75), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [604] = 11,
    ACTIONS(3), 1,
      sym_statement_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_expression_variable,
    ACTIONS(15), 1,
      sym_expression_number,
    STATE(30), 1,
      sym_expression,
    STATE(39), 1,
      sym_statement,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(38), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [646] = 11,
    ACTIONS(70), 1,
      sym_statement_skip,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_while,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      sym_expression_variable,
    ACTIONS(82), 1,
      sym_expression_number,
    STATE(60), 1,
      sym_expression,
    STATE(77), 1,
      sym_statement,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(75), 5,
      sym_statement_assignment,
      sym_statement_sequence,
      sym_statement_if_then_else,
      sym_statement_while_do,
      sym_statement_block,
  [688] = 9,
    ACTIONS(15), 1,
      sym_expression_number,
    ACTIONS(86), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_expression_variable,
    STATE(43), 1,
      sym_expression,
    STATE(68), 1,
      sym_predicate,
    ACTIONS(84), 2,
      sym_predicate_true,
      sym_predicate_false,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(66), 5,
      sym_predicate_negation,
      sym_predicate_conjunction,
      sym_predicate_disjunction,
      sym_predicate_comparison,
      sym_parenthesized_predicate,
  [725] = 9,
    ACTIONS(15), 1,
      sym_expression_number,
    ACTIONS(86), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_expression_variable,
    STATE(31), 1,
      sym_expression,
    STATE(69), 1,
      sym_predicate,
    ACTIONS(84), 2,
      sym_predicate_true,
      sym_predicate_false,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(66), 5,
      sym_predicate_negation,
      sym_predicate_conjunction,
      sym_predicate_disjunction,
      sym_predicate_comparison,
      sym_parenthesized_predicate,
  [762] = 9,
    ACTIONS(15), 1,
      sym_expression_number,
    ACTIONS(86), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_expression_variable,
    STATE(43), 1,
      sym_expression,
    STATE(72), 1,
      sym_predicate,
    ACTIONS(84), 2,
      sym_predicate_true,
      sym_predicate_false,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(66), 5,
      sym_predicate_negation,
      sym_predicate_conjunction,
      sym_predicate_disjunction,
      sym_predicate_comparison,
      sym_parenthesized_predicate,
  [799] = 9,
    ACTIONS(15), 1,
      sym_expression_number,
    ACTIONS(86), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_expression_variable,
    STATE(43), 1,
      sym_expression,
    STATE(73), 1,
      sym_predicate,
    ACTIONS(84), 2,
      sym_predicate_true,
      sym_predicate_false,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(66), 5,
      sym_predicate_negation,
      sym_predicate_conjunction,
      sym_predicate_disjunction,
      sym_predicate_comparison,
      sym_parenthesized_predicate,
  [836] = 9,
    ACTIONS(15), 1,
      sym_expression_number,
    ACTIONS(86), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_expression_variable,
    STATE(43), 1,
      sym_expression,
    STATE(62), 1,
      sym_predicate,
    ACTIONS(84), 2,
      sym_predicate_true,
      sym_predicate_false,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(66), 5,
      sym_predicate_negation,
      sym_predicate_conjunction,
      sym_predicate_disjunction,
      sym_predicate_comparison,
      sym_parenthesized_predicate,
  [873] = 9,
    ACTIONS(15), 1,
      sym_expression_number,
    ACTIONS(86), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_expression_variable,
    STATE(43), 1,
      sym_expression,
    STATE(65), 1,
      sym_predicate,
    ACTIONS(84), 2,
      sym_predicate_true,
      sym_predicate_false,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(66), 5,
      sym_predicate_negation,
      sym_predicate_conjunction,
      sym_predicate_disjunction,
      sym_predicate_comparison,
      sym_parenthesized_predicate,
  [910] = 9,
    ACTIONS(15), 1,
      sym_expression_number,
    ACTIONS(86), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_expression_variable,
    STATE(43), 1,
      sym_expression,
    STATE(71), 1,
      sym_predicate,
    ACTIONS(84), 2,
      sym_predicate_true,
      sym_predicate_false,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(66), 5,
      sym_predicate_negation,
      sym_predicate_conjunction,
      sym_predicate_disjunction,
      sym_predicate_comparison,
      sym_parenthesized_predicate,
  [947] = 9,
    ACTIONS(15), 1,
      sym_expression_number,
    ACTIONS(86), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_expression_variable,
    STATE(43), 1,
      sym_expression,
    STATE(74), 1,
      sym_predicate,
    ACTIONS(84), 2,
      sym_predicate_true,
      sym_predicate_false,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
    STATE(66), 5,
      sym_predicate_negation,
      sym_predicate_conjunction,
      sym_predicate_disjunction,
      sym_predicate_comparison,
      sym_parenthesized_predicate,
  [984] = 3,
    ACTIONS(92), 1,
      anon_sym_COLON_EQ,
    ACTIONS(44), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(42), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1006] = 6,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_PLUS,
    ACTIONS(100), 1,
      anon_sym_DASH,
    ACTIONS(96), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(94), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
  [1033] = 6,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_PLUS,
    ACTIONS(100), 1,
      anon_sym_DASH,
    ACTIONS(104), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
  [1060] = 8,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_PLUS,
    ACTIONS(100), 1,
      anon_sym_DASH,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      sym_comparison_operator,
    ACTIONS(106), 2,
      sym_lt,
      sym_gt,
    ACTIONS(108), 3,
      sym_le,
      sym_eq,
      sym_ge,
  [1088] = 1,
    ACTIONS(66), 11,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1102] = 1,
    ACTIONS(46), 11,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1116] = 3,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(50), 9,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1134] = 3,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(58), 9,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1152] = 1,
    ACTIONS(62), 11,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1166] = 1,
    ACTIONS(42), 11,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1180] = 2,
    ACTIONS(104), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
  [1195] = 3,
    ACTIONS(120), 1,
      anon_sym_SEMI,
    ACTIONS(118), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
  [1212] = 3,
    ACTIONS(120), 1,
      anon_sym_SEMI,
    ACTIONS(124), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
  [1229] = 2,
    ACTIONS(128), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(126), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
  [1244] = 3,
    ACTIONS(120), 1,
      anon_sym_SEMI,
    ACTIONS(132), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(130), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
  [1261] = 7,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_PLUS,
    ACTIONS(100), 1,
      anon_sym_DASH,
    STATE(55), 1,
      sym_comparison_operator,
    ACTIONS(106), 2,
      sym_lt,
      sym_gt,
    ACTIONS(108), 3,
      sym_le,
      sym_eq,
      sym_ge,
  [1286] = 3,
    ACTIONS(120), 1,
      anon_sym_SEMI,
    ACTIONS(136), 4,
      sym_statement_skip,
      anon_sym_if,
      anon_sym_while,
      sym_expression_variable,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_expression_number,
  [1303] = 4,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    STATE(61), 1,
      sym_expression,
    ACTIONS(82), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1321] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(29), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1339] = 5,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(140), 1,
      anon_sym_PLUS,
    ACTIONS(142), 1,
      anon_sym_DASH,
    ACTIONS(138), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [1359] = 4,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    STATE(34), 1,
      sym_expression,
    ACTIONS(82), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1377] = 4,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    STATE(35), 1,
      sym_expression,
    ACTIONS(82), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1395] = 4,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    STATE(36), 1,
      sym_expression,
    ACTIONS(82), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1413] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1431] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(64), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1449] = 4,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym_expression,
    ACTIONS(82), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1467] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(10), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1485] = 4,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    STATE(47), 1,
      sym_expression,
    ACTIONS(82), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(37), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1503] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1521] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1539] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(67), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_expression_variable,
      sym_expression_number,
    STATE(6), 5,
      sym_expression_addition,
      sym_expression_subtraction,
      sym_expression_multiplication,
      sym_expression_division,
      sym_parenthesized_expression,
  [1557] = 2,
    ACTIONS(144), 1,
      anon_sym_COLON_EQ,
    ACTIONS(42), 6,
      anon_sym_SEMI,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1569] = 5,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(140), 1,
      anon_sym_PLUS,
    ACTIONS(142), 1,
      anon_sym_DASH,
    ACTIONS(102), 2,
      anon_sym_SEMI,
      anon_sym_else,
  [1586] = 5,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(140), 1,
      anon_sym_PLUS,
    ACTIONS(142), 1,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_SEMI,
      anon_sym_else,
  [1603] = 1,
    ACTIONS(146), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [1611] = 1,
    ACTIONS(148), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [1619] = 5,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_PLUS,
    ACTIONS(100), 1,
      anon_sym_DASH,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
  [1635] = 2,
    ACTIONS(152), 1,
      anon_sym_and,
    ACTIONS(150), 4,
      anon_sym_then,
      anon_sym_do,
      anon_sym_or,
      anon_sym_RPAREN,
  [1645] = 1,
    ACTIONS(154), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [1653] = 5,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_PLUS,
    ACTIONS(100), 1,
      anon_sym_DASH,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
  [1669] = 1,
    ACTIONS(158), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [1677] = 3,
    ACTIONS(152), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
  [1687] = 1,
    ACTIONS(164), 3,
      anon_sym_LPAREN,
      sym_expression_variable,
      sym_expression_number,
  [1693] = 3,
    ACTIONS(152), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(166), 1,
      anon_sym_do,
  [1703] = 3,
    ACTIONS(152), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(168), 1,
      anon_sym_do,
  [1713] = 3,
    ACTIONS(152), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(170), 1,
      anon_sym_then,
  [1723] = 3,
    ACTIONS(152), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(172), 1,
      anon_sym_then,
  [1733] = 1,
    ACTIONS(102), 2,
      anon_sym_SEMI,
      anon_sym_else,
  [1738] = 2,
    ACTIONS(122), 1,
      anon_sym_else,
    ACTIONS(174), 1,
      anon_sym_SEMI,
  [1745] = 2,
    ACTIONS(174), 1,
      anon_sym_SEMI,
    ACTIONS(176), 1,
      anon_sym_else,
  [1752] = 2,
    ACTIONS(174), 1,
      anon_sym_SEMI,
    ACTIONS(178), 1,
      anon_sym_else,
  [1759] = 2,
    ACTIONS(116), 1,
      anon_sym_else,
    ACTIONS(174), 1,
      anon_sym_SEMI,
  [1766] = 1,
    ACTIONS(126), 2,
      anon_sym_SEMI,
      anon_sym_else,
  [1771] = 2,
    ACTIONS(130), 1,
      anon_sym_else,
    ACTIONS(174), 1,
      anon_sym_SEMI,
  [1778] = 1,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
  [1782] = 1,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
  [1786] = 1,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
  [1790] = 1,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 146,
  [SMALL_STATE(6)] = 194,
  [SMALL_STATE(7)] = 219,
  [SMALL_STATE(8)] = 244,
  [SMALL_STATE(9)] = 273,
  [SMALL_STATE(10)] = 302,
  [SMALL_STATE(11)] = 327,
  [SMALL_STATE(12)] = 352,
  [SMALL_STATE(13)] = 394,
  [SMALL_STATE(14)] = 436,
  [SMALL_STATE(15)] = 478,
  [SMALL_STATE(16)] = 520,
  [SMALL_STATE(17)] = 562,
  [SMALL_STATE(18)] = 604,
  [SMALL_STATE(19)] = 646,
  [SMALL_STATE(20)] = 688,
  [SMALL_STATE(21)] = 725,
  [SMALL_STATE(22)] = 762,
  [SMALL_STATE(23)] = 799,
  [SMALL_STATE(24)] = 836,
  [SMALL_STATE(25)] = 873,
  [SMALL_STATE(26)] = 910,
  [SMALL_STATE(27)] = 947,
  [SMALL_STATE(28)] = 984,
  [SMALL_STATE(29)] = 1006,
  [SMALL_STATE(30)] = 1033,
  [SMALL_STATE(31)] = 1060,
  [SMALL_STATE(32)] = 1088,
  [SMALL_STATE(33)] = 1102,
  [SMALL_STATE(34)] = 1116,
  [SMALL_STATE(35)] = 1134,
  [SMALL_STATE(36)] = 1152,
  [SMALL_STATE(37)] = 1166,
  [SMALL_STATE(38)] = 1180,
  [SMALL_STATE(39)] = 1195,
  [SMALL_STATE(40)] = 1212,
  [SMALL_STATE(41)] = 1229,
  [SMALL_STATE(42)] = 1244,
  [SMALL_STATE(43)] = 1261,
  [SMALL_STATE(44)] = 1286,
  [SMALL_STATE(45)] = 1303,
  [SMALL_STATE(46)] = 1321,
  [SMALL_STATE(47)] = 1339,
  [SMALL_STATE(48)] = 1359,
  [SMALL_STATE(49)] = 1377,
  [SMALL_STATE(50)] = 1395,
  [SMALL_STATE(51)] = 1413,
  [SMALL_STATE(52)] = 1431,
  [SMALL_STATE(53)] = 1449,
  [SMALL_STATE(54)] = 1467,
  [SMALL_STATE(55)] = 1485,
  [SMALL_STATE(56)] = 1503,
  [SMALL_STATE(57)] = 1521,
  [SMALL_STATE(58)] = 1539,
  [SMALL_STATE(59)] = 1557,
  [SMALL_STATE(60)] = 1569,
  [SMALL_STATE(61)] = 1586,
  [SMALL_STATE(62)] = 1603,
  [SMALL_STATE(63)] = 1611,
  [SMALL_STATE(64)] = 1619,
  [SMALL_STATE(65)] = 1635,
  [SMALL_STATE(66)] = 1645,
  [SMALL_STATE(67)] = 1653,
  [SMALL_STATE(68)] = 1669,
  [SMALL_STATE(69)] = 1677,
  [SMALL_STATE(70)] = 1687,
  [SMALL_STATE(71)] = 1693,
  [SMALL_STATE(72)] = 1703,
  [SMALL_STATE(73)] = 1713,
  [SMALL_STATE(74)] = 1723,
  [SMALL_STATE(75)] = 1733,
  [SMALL_STATE(76)] = 1738,
  [SMALL_STATE(77)] = 1745,
  [SMALL_STATE(78)] = 1752,
  [SMALL_STATE(79)] = 1759,
  [SMALL_STATE(80)] = 1766,
  [SMALL_STATE(81)] = 1771,
  [SMALL_STATE(82)] = 1778,
  [SMALL_STATE(83)] = 1782,
  [SMALL_STATE(84)] = 1786,
  [SMALL_STATE(85)] = 1790,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statements, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_addition, 3, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_addition, 3, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_subtraction, 3, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_subtraction, 3, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_multiplication, 3, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_multiplication, 3, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_division, 3, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_division, 3, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_assignment, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_assignment, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_while_do, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_while_do, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_if_then_else, 6, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_if_then_else, 6, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_block, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_block, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_sequence, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_sequence, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statements_repeat1, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_statements_repeat1, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_comparison, 3, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_conjunction, 3, 0, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_predicate, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_disjunction, 3, 0, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_negation, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_operator, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [182] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_while(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
